name: Publish to PyPI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Publish ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ros2-pkg-create]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: python3 -m pip install --user build
    - name: Build wheel and tarball
      run: python3 -m build --sdist --wheel --outdir dist/ ${{ matrix.package }}
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.10.1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.10.1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true
    # `continue-on-error` needed cause `skip-existing: true` is not honored
    # https://github.com/pypa/gh-action-pypi-publish/issues/201
    continue-on-error: true